apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/component: 10536252-ca-mongo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo
      app.kubernetes.io/component: 10536252-ca-mongo
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo
        app.kubernetes.io/component: 10536252-ca-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        args:
          - --bind_ip
          - 0.0.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
   service-label: ca-backend-cluster-service
  name: ca-frontend-cluster-service
spec:
  type: ClusterIP
  ports:
  - name: ca-backend-service-port
    port: 27017
    protocol: TCP
  selector:
    deployment-name: 10536252-ca-mongo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: ca-backend-cluster-service
  name: application-frontend-cluster-service-loadbalancer
spec: 
  type: LoadBalancer
  ports:
  - name: ca-frontend-load-balancer-service-port
    port: 27017
    protocol: TCP
  selector:
    deployment-name: 10536252-ca-mongo
 