apiVersion: apps/v1
kind: Deployment
metadata:
  name: b8it148-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment-name: v1-demo
  template:
    metadata:
      labels:
        deployment-name: v1-demo
    spec:
      containers:
      - name: b8it148-kubernetes-container
        image: radekszwajca/nowy:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: b8ot148-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    deployment-name: v1-demo
  ports:
  - port: 8088
    targetPort: 8088
    nodePort: 30001
